### ISSUE TITLE
GPU configuration

### ISSUE THREAD

**Issue by DhavalRepo18** [ZitongYang/Synthetic_Continued_Pretraining#1]
I read paper and did not find the hardware section on amount of time and GPU configuration for model discussed in the paper. Can you please provide the configuration as well as time it took for completing the pre-training.

**Comment by ZitongYang** [comment]
Hi,

We have updated our arXiv preprint with this detail mentioned in the last paragraph of Appendix C. The training of EntiGraph CPT model took 41 hours excluding evaluation and checkpointing time.

We have alsor released the weights of this trained model at  https://huggingface.co/zitongyang/llama-3-8b-entigraph-quality
