### ISSUE TITLE
Benchmarks to show performance improvement

### ISSUE THREAD

**Issue by XcloudFance** [ZitongYang/Synthetic_Continued_Pretraining#2]
Hi and thanks your solid contribution to synthetic efficient data.

I wonder if there is any benchmark or tables to be referred for the performance of LLMs using entigraph?

I am really looking forward to seeing the effectiveness of this work.

**Comment by ZitongYang** [comment]
Thanks for your interest in our work. The benchmark we have used in the paper is QuALITY QA set, the code to evaluate on it is included here https://github.com/ZitongYang/Synthetic_Continued_Pretraining?tab=readme-ov-file#step-5-evaluation-on-quality-qa-set
